### Add book
POST localhost:8080/addBook
Content-Type: application/json

{
  "name" : "Java Performance by Vladimir Sonkin, 2022"
}

### Add book
POST localhost:8080/addBook
Content-Type: application/json

{
  "title" : "Test book"
}


### get all books
GET localhost:8080/books

### initialize books
POST localhost:8080/generate/10000

### similar
GET localhost:8080/similar/stream/Java Sonkin

### similar 2
GET localhost:8080/similar/predicate/Java Sonkin